export const environment = {
  production: true,
  environemnt: 'Production',
  loginURL: `https://nks-maintenance.online/Server/public/index1.php/users/login`,
  forgotPasswordURL: 'https://nks-maintenance.online/Server/public/index1.php/users/forgotpassword',
  registerAccountURL: 'https://nks-maintenance.online/Server/public/index1.php/users/registeraccount',
  resetPasswordURL: 'https://nks-maintenance.online/Server/public/index1.php/users/resetaccountpassword',
  accountChangeURL: '',
  avaliableDocumentsURL: '',
  getDocumentInformationURL: '',
  avaliableIncompleteDocumentsURL: '',
  getIncompleteDocumentInformationURL: '',
  submitValueURL: '',
  avaliableCompletedDocumentsURL: '',
  getCompletedDocumentURL: '',
  avaliableReviewDocumentsURL: '',
  getReviewDocumentURL: '',
  submitDocument: '',
  submitReview: '',
  getGraphInfo: '',
  getGraphData: '',
};
