export const environment = {
  production: false,
  environemnt: 'Dreamhost',
  loginURL: 'https://nks-maintenance.online/Server/public/router.php/users/login',
  forgotPasswordURL: 'https://nks-maintenance.online/Server/public/router.php/users/forgotpassword',
  registerAccountURL: 'https://nks-maintenance.online/Server/public/router.php/users/registeraccount',
  resetPasswordURL: 'https://nks-maintenance.online/Server/public/router.php/users/resetaccountpassword',
  accountChangeURL: '/',
  avaliableDocumentsURL: 'https://nks-maintenance.online/Server/public/router.php/documents/getAvaliableNew',
  getDocumentInformationURL: 'https://nks-maintenance.online/Server/public/router.php/documents/getNewDocument',
  avaliableIncompleteDocumentsURL: 'https://nks-maintenance.online/Server/public/router.php/documents/getAllIncomplete',
  getIncompleteDocumentInformationURL: 'https://nks-maintenance.online/Server/public/router.php/documents/getIncompleteDocument',
  submitValueURL: 'https://nks-maintenance.online/Server/public/router.php/documents/submitNewValue',
  submitCommentURL: 'https://nks-maintenance.online/Server/public/router.php/documents/submitComment',
  avaliableReviewDocumentsURL: 'https://nks-maintenance.online/Server/public/router.php/documents/getAvaliableReview',
  getReviewDocumentURL: 'https://nks-maintenance.online/Server/public/router.php/documents/getReviewDocument',
  submitDocument: 'https://nks-maintenance.online/Server/public/router.php/documents/saveCompletedDocument',
  submitReview: 'https://nks-maintenance.online/Server/public/router.php/documents/submitReviewDocument',
  submitNotificationURL: '',
  getGraphInfo: 'https://nks-maintenance.online/Server/public/router.php/data/getTaskNames',
  getGraphData: 'https://nks-maintenance.online/Server/public/router.php/data/getDataForGraph',
};
