export const environment = {
  production: false,
  environemnt: 'LocalApache',
  loginURL: `http://localhost:8081/Server/public/router.php/users/login`,
  forgotPasswordURL: 'http://localhost:8081/Server/public/router.php/users/forgotpassword',
  registerAccountURL: 'http://localhost:8081/Server/public/router.php/users/registeraccount',
  resetPasswordURL: 'http://localhost:8081/Server/public/router.php/users/resetaccountpassword',
  accountChangeURL: '/',
  avaliableDocumentsURL: 'http://localhost:8081/Server/public/router.php/documents/getAvaliableNew',
  getDocumentInformationURL: 'http://localhost:8081/Server/public/router.php/documents/getNewDocument',
  avaliableIncompleteDocumentsURL: 'http://localhost:8081/Server/public/router.php/documents/getAllIncomplete',
  getIncompleteDocumentInformationURL: 'http://localhost:8081/Server/public/router.php/documents/getIncompleteDocument',
  submitValueURL: 'http://localhost:8081/Server/public/router.php/documents/submitNewValue',
  submitCommentURL: 'http://localhost:8081/Server/public/router.php/documents/submitComment',
  avaliableReviewDocumentsURL: 'http://localhost:8081/Server/public/router.php/documents/getAvaliableReview',
  getReviewDocumentURL: 'http://localhost:8081/Server/public/router.php/documents/getReviewDocument',
  submitDocument: 'http://localhost:8081/Server/public/router.php/documents/saveCompletedDocument',
  submitReview: 'http://localhost:8081/Server/public/router.php/documents/submitReviewDocument',
  submitNotificationURL: '',
  getGraphInfo: 'http://localhost:8081/Server/public/router.php/data/getTaskNames',
  getGraphData: 'http://localhost:8081/Server/public/router.php/data/getDataForGraph',
};
